### ISSUE TITLE
New Experimental Bundle Support Missing An Output

### ISSUE THREAD

**Issue by HypnoticMelody** [afarra6/godOSC#4]
In my testing of the new update, I'm supplying Godot with an OSC bundle with a bunch of information, but in each message in the bundle, the third value is lost and is just outputted as zero.

It outputs this error once on program start:
```
E 0:00:01:0270   OSCServer.gd:116 @ parse_bundle(): Condition "begin > end" is true. Returning: result
  <C++ Source>   ./core/templates/vector.h:174 @ slice()
  <Stack Trace>  OSCServer.gd:116 @ parse_bundle()
                 OSCServer.gd:48 @ parse()
                 OSCServer.gd:38 @ _process()
```

And it outputs this error constantly:

```
E 0:00:01:0046   OSCServer.gd:146 @ parse_bundle(): Condition "p_offset < 0 || p_offset > (int64_t(size) - 4)" is true. Returning: 0
  <C++ Source>   core/variant/variant_call.cpp:833 @ func_PackedByteArray_decode_float()
  <Stack Trace>  OSCServer.gd:146 @ parse_bundle()
                 OSCServer.gd:48 @ parse()
                 OSCServer.gd:38 @ _process()
```

**Comment by dfcompose** [comment]
I _believe_ I've fixed this now, I had made an error with slice points (whoops). 

![image](https://github.com/afarra6/godOSC/assets/133391238/d652f864-5561-4a79-82e4-3b6d1b6cd002)


I've gotten it to output correctly with sending 6 osc messages with various argument amounts and data types. Let me know if this fixes the issue on your end!

**Comment by HypnoticMelody** [comment]
It works now! Thank you so much!!! My program is now fully working thanks to you!!!! Thank you so much!!!!!!
