### ISSUE TITLE
Position.X stops moving when OSC Server is connected

### ISSUE THREAD

**Issue by OrdinaireX** [afarra6/godOSC#5]
Hey there,

I'm getting an issue where when I activate OSC in my other program (TouchDesigner), the cube stops moving in the Demo Scene you provided. When I disable it, the cube starts moving again. The OSC messages are received in TouchDesigner, but the visual data stops responding in Godot 4.3

Any idea how I could fix this? Am I doing something wrong?

Thanks!

**Comment by dfcompose** [comment]
Hmm, it's hard to tell exactly what might be going wrong based on your description. The first thing you may want to check is if TouchDesigner is creating its own OSC Server on the same port (4646) that the demo scene is. You could try to set the OSCServer node's port to something different, like port 7177 and then sending to port 7177 from TouchDesigner. If you could share a video of what's going on that might be helpful as well!


Oh actually, try deleting the sliders from the demo.  They are probably sending conflicting OSC messages. I'll fix that for future releases. Let me know if that's not the problem.

**Comment by ghost** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by dfcompose** [comment]
After some more poking around, I think how I had originally made OSCMessage was causing some issues. The most recent version has an updated OSCMessage that allows enabling/disabling it from sending messages, I think this might fix your issue as the OSCMessage nodes attached to the sliders were sending OSC messages every frame no matter if the slider was being moved or not.

**Comment by OrdinaireX** [comment]
Hey I appreciate the added functionality, but unfortunately the issue still persists.

Admittedly I'm new to Godot, but it seems like the OSC Receiver might be the culprit. When switching the port in TouchDesigner, responsiveness in Godot immediately comes back, but when on the same port only the OSC messages come through. Perhaps the OSC Receiver defaults to the server and stops sending to the parent node when the Network Port is accessed.

In my use case, I'd like an OSCMessage Node to be attached to my CharacterBody2D, so I could get the XY position of the character as an OSC message in TouchDesigner.

This OSC plugin could provide so much potential for people in the creative tech/live visual space with TouchDesigner. Thank you for releasing this plugin. [Here you can see the issue.](https://youtu.be/x9dI8Zii-zQ)

**Comment by dfcompose** [comment]
Ah I see the issue. You can only have one OSC server open per port. This is system wide, not just in Godot so it's an OSC issue not a Godot issue. When you start OSC in TouchDesigner you're using port 4646 essentially blocking Godot from receiving OSC on that same port. This is why the cubes start moving again when you change the port to 4647 in TouchDesigner but don't move when it's set to port 4646. The solution would be to make a second OSCMessage that sends to TouchDesigner on a different port than 4646, so something like this:


HSlider
-OSCMessage (sending to port 4646)
-OSCMessage (sending to port 7177) [the easiest way to do this would be to just copy paste the original OSCMessage]


Where the OSC port in TouchDesigner is set to 7177. In most use cases this issue would never arise, as you'll typically not use OSC to communicate between entities in Godot, but the demo scene is set up to do just that for demonstration purposes. Thanks for bringing this to my attention though as it obviously has caused some confusion, I may rework the demo scene to make it clearer how to go about using OSC with Godot, not just how the OSC nodes work.

**Comment by OrdinaireX** [comment]
Hey I got it working in the demo scene by doubling up on everything, one instance each for Touch and Godot. Curious to see how it scales through the project haha.

Thank you so much for your help. I know its a weird use case but I'm grateful for the functionality and help. Take care!
